pipeline {
    agent any

    parameters {
        choice(
            name: 'ACTION',
            choices: ['apply', 'destroy'],
            description: 'Choose Terraform action'
        )
    }

    environment {
        AWS_DEFAULT_REGION = "ap-south-1"
        TF_DIR = "terraformProject/main"
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/durveshyadav3604/cloud-devops-project.git',
                    credentialsId: 'github-token'
            }
        }

        stage('Terraform Init') {
            steps {
                withCredentials([
                    [
                        $class: 'AmazonWebServicesCredentialsBinding',
                        credentialsId: 'aws-terraform-creds'
                    ]
                ]) {
                    dir("${TF_DIR}") {
                        sh '''
                          export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
                          export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
                          export AWS_DEFAULT_REGION=ap-south-1

                          terraform init -reconfigure
                        '''
                    }
                }
            }
        }

        stage('Terraform Plan') {
            when {
                expression { params.ACTION == 'apply' }
            }
            steps {
                withCredentials([
                    [
                        $class: 'AmazonWebServicesCredentialsBinding',
                        credentialsId: 'aws-terraform-creds'
                    ]
                ]) {
                    dir("${TF_DIR}") {
                        sh '''
                          export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
                          export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
                          export AWS_DEFAULT_REGION=ap-south-1

                          terraform plan -out=tfplan
                        '''
                    }
                }
            }
        }

        stage('Terraform Apply or Destroy') {
            steps {
                input message: "Are you sure you want to ${params.ACTION} Terraform resources?"

                withCredentials([
                    [
                        $class: 'AmazonWebServicesCredentialsBinding',
                        credentialsId: 'aws-terraform-creds'
                    ]
                ]) {
                    dir("${TF_DIR}") {
                        sh '''
                          export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
                          export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
                          export AWS_DEFAULT_REGION=ap-south-1

                          if [ "${ACTION}" = "apply" ]; then
                              terraform apply -auto-approve tfplan
                          else
                              terraform destroy -auto-approve
                          fi
                        '''
                    }
                }
            }
        }
    }

    post {
        success {
            echo " Terraform ${params.ACTION} completed successfully"
        }
        failure {
            echo " Terraform ${params.ACTION} failed"
        }
    }
}

