pipeline {
    agent any

    parameters {
        choice(
            name: 'ACTION',
            choices: ['apply', 'destroy'],
            description: 'Terraform action'
        )
    }

    environment {
        AWS_REGION         = "ap-south-1"
        AWS_DEFAULT_REGION = "ap-south-1"
        TF_DIR             = "terraformProject/main"
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/durveshyadav3604/cloud-devops-project.git',
                    credentialsId: 'github-token'
            }
        }

        stage('Terraform Init') {
            steps {
                withCredentials([[ 
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'aws-terraform-creds'
                ]]) {
                    dir("${TF_DIR}") {
                        sh '''
                          echo "🔐 Verifying AWS identity..."
                          aws sts get-caller-identity

                          echo "🚀 Initializing Terraform..."
                          rm -rf .terraform
                          terraform init -reconfigure
                        '''
                    }
                }
            }
        }

        stage('Terraform Plan') {
            when {
                expression { params.ACTION == 'apply' }
            }
            steps {
                withCredentials([[ 
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'aws-terraform-creds'
                ]]) {
                    dir("${TF_DIR}") {
                        sh 'terraform plan -out=tfplan'
                    }
                }
            }
        }

        stage('Terraform Apply / Destroy') {
            steps {
                input message: "Confirm Terraform ${params.ACTION}?"

                withCredentials([[ 
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'aws-terraform-creds'
                ]]) {
                    dir("${TF_DIR}") {
                        sh '''
                          if [ "${ACTION}" = "apply" ]; then
                              terraform apply -auto-approve tfplan
                          else
                              terraform destroy -auto-approve
                          fi
                        '''
                    }
                }
            }
        }
    }

    post {
        success {
            echo " Terraform ${params.ACTION} completed successfully"
        }
        failure {
            echo " Terraform ${params.ACTION} failed"
        }
    }
}

